# Generated by Django 5.2.17 on 2026-09-09 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditevent_expense_created_at_expense_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='submission_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='expense',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='submission_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('created_by__isnull', True), ('amount__gt', 0), _connector='OR'), name='new_expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('created_by__isnull', True), ('amount__gt', 0), _connector='OR'), name='new_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('transaction_reference', ''), _negated=True), ('status__in', ['pending', 'confirmed'])), fields=('method', 'transaction_reference'), name='unique_live_payment_transaction'),
        ),
    ]
