# Generated by Django 5.2.17 on 2026-09-10 05:48

import django.db.models.deletion
import uuid
import re
from django.conf import settings
from django.db import migrations, models


def normalize_existing_phones(apps, schema_editor):
    # Freeze normalization here so later application changes don't alter migrations.
    # Preserve invalid legacy values and duplicates; ambiguous logins are rejected.
    Profile = apps.get_model('core', 'UserProfile')
    profiles = Profile.objects.using(schema_editor.connection.alias)
    for profile in profiles.exclude(phone='').iterator():
        value = profile.phone.strip()
        if not re.fullmatch(r'[+0-9 ()-]+', value):
            continue
        compact = re.sub(r'[ ()-]', '', value)
        if re.fullmatch(r'[6-9][0-9]{9}', compact):
            compact = '+91' + compact
        elif re.fullmatch(r'91[6-9][0-9]{9}', compact):
            compact = '+' + compact
        elif not re.fullmatch(r'\+[1-9][0-9]{7,14}', compact):
            continue
        if compact.startswith('+91') and not re.fullmatch(r'\+91[6-9][0-9]{9}', compact):
            continue
        profiles.filter(pk=profile.pk).update(phone=compact)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expense_submission_hash_expense_submission_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('version', models.UUIDField(default=uuid.uuid4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(normalize_existing_phones, migrations.RunPython.noop),
    ]
